repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: ["."]